Security/CVE fixes kw 27 (#56)
* version bump + ran PK

* Update exasol-testcontainers & add exception to ossindex plugin for false positive CVE-2024-55551

* Replace deprecated functions with newer equivalent

* PK version doc fix

* Customize verify release artifacts step

* changes to verification step

* Added matrix build + set runner to explicit version

* Finish changes file

* pk file include apparmor step

* fix PK file + run pk fix to update project-keeper yml file

* changes to .gitattributes file after updating workflows

* Added security.md to attributes

* Fix release date

* Update version matrix in pk file + run pk

* Release date ...

diff --git a/.github/workflows/ci-build.yml b/.github/workflows/ci-build.yml
--- a/.github/workflows/ci-build.yml
+++ b/.github/workflows/ci-build.yml
@@ -1,61 +1,279 @@
-# Generated by Project Keeper
-# https://github.com/exasol/project-keeper/blob/main/project-keeper/src/main/resources/templates/.github/workflows/ci-build.yml
+# This file was generated by Project Keeper.
 name: CI Build
 on:
   push:
-    branches:
-      - main
+    branches: [
+      main
+    ]
+    
   pull_request:
-
+    types: [
+      opened,
+      synchronize,
+      reopened,
+      ready_for_review
+    ]
+    
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    concurrency:
-      group: ${{ github.workflow }}-${{ github.ref }}
+  matrix-build:
+    runs-on: ubuntu-24.04
+    defaults:
+      run: {
+        shell: bash
+      }
+    permissions: {
+      contents: read
+    }
+    concurrency: {
+      group: '${{ github.workflow }}-${{ github.ref }}-${{ matrix.exasol_db_version }}',
       cancel-in-progress: true
+    }
+    strategy:
+      fail-fast: false
+      matrix:
+        exasol_db_version: [
+          8.34.0,
+          7.1.30
+        ]
+        
+    env: {
+      DEFAULT_EXASOL_DB_VERSION: 8.34.0
+    }
     steps:
       - name: Free Disk Space
+        id: free-disk-space
         if: ${{ false }}
         run: |
           sudo rm -rf /usr/local/lib/android
           sudo rm -rf /usr/share/dotnet
       - name: Checkout the repository
+        id: checkout
         uses: actions/checkout@v4
-        with:
+        with: {
           fetch-depth: 0
+        }
       - name: Set up JDKs
+        id: setup-java
         uses: actions/setup-java@v4
         with:
-          distribution: "temurin"
-          java-version: |
+          distribution: temurin
+          java-version: |-
             11
             17
-          cache: "maven"
+          cache: maven
       - name: Cache SonarCloud packages
-        uses: actions/cache@v3
-        with:
-          path: ~/.sonar/cache
-          key: ${{ runner.os }}-sonar
-          restore-keys: ${{ runner.os }}-sonar
-      - name: Enable testcontainer reuse
+        id: cache-sonar
+        uses: actions/cache@v4
+        with: {
+          path: ~/.sonar/cache,
+          key: '${{ runner.os }}-sonar',
+          restore-keys: '${{ runner.os }}-sonar'
+        }
+      - {
+        name: Enable testcontainer reuse,
+        id: enable-testcontainer-reuse,
         run: echo 'testcontainers.reuse.enable=true' > "$HOME/.testcontainers.properties"
+      }
+      - {
+        name: Fix "VM Crashed" error by allowing unprivileged user namespaces,
+        id: fix-vm-crashed,
+        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
+      }
       - name: Run tests and build with Maven
+        id: build-pk-verify
         run: |
           mvn --batch-mode clean verify \
               -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
-              -DtrimStackTrace=false
-      - name: Publish Test Report
-        uses: scacap/action-surefire-report@v1
-        if: ${{ always() && github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]' }}
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+              -DtrimStackTrace=false \
+              -Dcom.exasol.dockerdb.image=${{ matrix.exasol_db_version }}
+        env: {
+          EXASOL_DB_VERSION: '${{ matrix.exasol_db_version }}'
+        }
       - name: Sonar analysis
-        if: ${{ env.SONAR_TOKEN != null }}
+        id: sonar-analysis
+        if: ${{ env.SONAR_TOKEN != null && matrix.exasol_db_version == env.DEFAULT_EXASOL_DB_VERSION }}
         run: |
           mvn --batch-mode org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
               -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
               -DtrimStackTrace=false \
               -Dsonar.token=$SONAR_TOKEN
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        env: {
+          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}',
+          SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
+        }
+      - name: Verify Release Artifacts
+        id: verify-release-artifacts
+        run: |
+          print_message() {
+              local -r message="$1"
+              echo "$message"
+              echo "$message" >> "$GITHUB_STEP_SUMMARY"
+          }
+
+          print_message "### Release Artifacts"
+
+          IFS=$'\n' read -r -a artifacts_array <<<"$ARTIFACTS"
+          missing_files=()
+          allowed_missing_patterns=(
+            "testing-tutorial/target"  # Add patterns you want to exempt here
+          )
+
+          is_allowed_missing() {
+              local file="$1"
+              for pattern in "${allowed_missing_patterns[@]}"; do
+                  if [[ "$file" == *"$pattern"* ]]; then
+                      return 0
+                  fi
+              done
+              return 1
+          }
+
+          for file in "${artifacts_array[@]}"; do
+              echo "Checking if file $file exists..."
+              if [[ ! -f "$file" ]]; then
+                  if is_allowed_missing "$file"; then
+                      print_message "* ⚠️ \`$file\` is missing but allowed ⚠️"
+                  else
+                      print_message "* ⚠️ \`$file\` does not exist ⚠️"
+                      echo "Content of directory $(dirname "$file"):"
+                      ls "$(dirname "$file")"
+                      missing_files+=("$file")
+                  fi
+              else
+                  print_message "* \`$file\` ✅"
+              fi
+          done
+
+          print_message ""
+          number_of_missing_files=${#missing_files[@]}
+          if [[ $number_of_missing_files -gt 0 ]]; then
+              print_message "⚠️ $number_of_missing_files release artifact(s) missing ⚠️"
+              exit 1
+          fi
+        env: {
+          ARTIFACTS: '${{ steps.build-pk-verify.outputs.release-artifacts }}'
+        }
+      - name: Upload artifacts
+        id: upload-artifacts
+        uses: actions/upload-artifact@v4
+        with: {
+          name: 'artifacts-exasol-${{ matrix.exasol_db_version }}',
+          path: '${{ steps.build-pk-verify.outputs.release-artifacts }}',
+          retention-days: 5
+        }
+      - name: Configure broken links checker
+        id: configure-link-check
+        run: |
+          mkdir -p ./target
+          echo '{"aliveStatusCodes": [429, 200], "ignorePatterns": [' \
+               '{"pattern": "^https?://(www|dev).mysql.com/"},' \
+               '{"pattern": "^https?://(www.)?opensource.org"}' \
+               '{"pattern": "^https?://(www.)?eclipse.org"}' \
+               '{"pattern": "^https?://projects.eclipse.org"}' \
+               ']}' > ./target/broken_links_checker.json
+      - uses: gaurav-nelson/github-action-markdown-link-check@v1
+        id: run-link-check
+        with: {
+          use-quiet-mode: yes,
+          use-verbose-mode: yes,
+          config-file: ./target/broken_links_checker.json
+        }
+  next-java-compatibility:
+    runs-on: ubuntu-latest
+    defaults:
+      run: {
+        shell: bash
+      }
+    permissions: {
+      contents: read
+    }
+    concurrency: {
+      group: '${{ github.workflow }}-next-java-${{ github.ref }}',
+      cancel-in-progress: true
+    }
+    steps:
+      - name: Checkout the repository
+        id: checkout
+        uses: actions/checkout@v4
+        with: {
+          fetch-depth: 0
+        }
+      - name: Set up JDK 17
+        id: setup-java
+        uses: actions/setup-java@v4
+        with: {
+          distribution: temurin,
+          java-version: '17',
+          cache: maven
+        }
+      - {
+        name: Run tests and build with Maven 17,
+        id: build-next-java,
+        run: mvn --batch-mode clean package -DtrimStackTrace=false -Djava.version=17
+      }
+  build:
+    needs: [
+      matrix-build,
+      next-java-compatibility
+    ]
+    runs-on: ubuntu-latest
+    defaults:
+      run: {
+        shell: bash
+      }
+    permissions: {
+      contents: read,
+      issues: read
+    }
+    outputs: {
+      release-required: '${{ steps.check-release.outputs.release-required }}'
+    }
+    steps:
+      - name: Checkout the repository
+        id: checkout
+        uses: actions/checkout@v4
+        with: {
+          fetch-depth: 0
+        }
+      - name: Set up JDKs
+        id: setup-java
+        uses: actions/setup-java@v4
+        with:
+          distribution: temurin
+          java-version: |-
+            11
+            17
+          cache: maven
+      - name: Check if release is needed
+        id: check-release
+        if: ${{ github.ref == 'refs/heads/main' }}
+        run: |
+          if mvn --batch-mode com.exasol:project-keeper-maven-plugin:verify-release --projects .; then
+              echo "### ✅ Release preconditions met, start release" >> "$GITHUB_STEP_SUMMARY"
+              echo "release-required=true" >> "$GITHUB_OUTPUT"
+          else
+              echo "### 🛑 Not all release preconditions met, skipping release" >> "$GITHUB_STEP_SUMMARY"
+              echo "See log output for details." >> "$GITHUB_STEP_SUMMARY"
+              echo "release-required=false" >> "$GITHUB_OUTPUT"
+          fi
+        env: {
+          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
+        }
+  start_release:
+    needs: build
+    if: ${{ github.ref == 'refs/heads/main' && needs.build.outputs.release-required == 'true' }}
+    concurrency: {
+      cancel-in-progress: false,
+      group: release
+    }
+    secrets: inherit
+    permissions: {
+      contents: write,
+      actions: read,
+      issues: read
+    }
+    uses: ./.github/workflows/release.yml
+    with: {
+      started-from-ci: true,
+      maven-central-auto-publish: true
+    }
